# Generated by Django 4.2.6 on 2023-11-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserReport', '0004_alter_summarydata_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarydata',
            options={'ordering': ['-upload_date']},
        ),
    ]
